name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore src/MobileDocKit.sln
    - name: Build
      run: dotnet build src/MobileDocKit.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/MobileDocKit.sln --no-restore --verbosity normal
    - name: Package
      run: dotnet pack src/MobileDocKit/MobileDocKit.csproj -c Release -o packages/
    - name: Publish package
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/wmeints/index.json -n github -u wmeints -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget push "packages/*.nupkg" --source "github" -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate