name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore src/MobileDocKit.sln
    - name: Build
      run: dotnet build src/MobileDocKit.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/MobileDocKit.sln --no-restore --verbosity normal
    - name: Package
      run: dotnet pack src/MobileDocKit/MobileDocKit.csproj -c Release -o packages/
