name: Publish package

on:
  push:
    tags: *
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract version number
      id: determineVersionNumber
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '')
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore src/MobileDocKit.sln
    - name: Package
      run: dotnet pack src/MobileDocKit/MobileDocKit.csproj -c Release -o packages/ /p:Version=${{ steps.determineVersionNumber.outputs.result }}
    - name: Publish package
          run: |
            dotnet nuget add source https://nuget.pkg.github.com/wmeints/index.json -n github -u wmeints -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
            dotnet nuget push "packages/*.nupkg" --source "github" -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate